// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@2.0.2";

// src/lib/mcp/tools/list-inquiries.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@2.0.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-inquiries.ts
var list_inquiries_default = defineTool({
  name: "list_inquiries",
  title: "List inquiries",
  description: "List customer inquiries sent from the belt conveyor or profile cutting configurator, newest first.",
  inputSchema: {
    tool: z.enum(["belt", "profile"]).describe("Which configurator the inquiries came from."),
    limit: z.number().int().min(1).max(50).default(10).describe("Maximum number of inquiries.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tool, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const table = tool === "belt" ? "belt_inquiries" : "profile_inquiries";
    const { data, error } = await supabaseForUser(ctx).from(table).select("id, created_at, reference, name, company, email, phone, message, lang, summary_text").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { inquiries: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-configurator-references.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.0.2";
import { z as z2 } from "npm:zod@^3.25.76";
var list_configurator_references_default = defineTool2({
  name: "list_configurator_references",
  title: "List configuration references",
  description: "List reserved configuration reference IDs (FT-YYYYMMDD-NNN) with their saved configuration and whether a PDF or inquiry followed.",
  inputSchema: {
    tool: z2.enum(["belt", "profile"]).optional().describe("Filter by configurator."),
    reference: z2.string().trim().min(1).optional().describe("Look up one exact reference ID."),
    limit: z2.number().int().min(1).max(50).default(10).describe("Maximum number of rows.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tool, reference, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("configurator_references").select("reference, tool, lang, configuration, pdf_downloaded_at, inquiry_sent_at, created_at").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (tool) query = query.eq("tool", tool);
    if (reference) query = query.eq("reference", reference);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { references: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-pricing-components.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.0.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_pricing_components_default = defineTool3({
  name: "list_pricing_components",
  title: "List pricing components",
  description: "List the priced components of a configurator (key, labels, unit, price in EUR, article number, price source). Requires an account with pricing access.",
  inputSchema: {
    tool: z3.enum(["belt", "profile"]).default("belt").describe("Which configurator's price list."),
    includeInactive: z3.boolean().default(false).describe("Also return deactivated components.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tool, includeInactive }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("pricing_components").select("key, tool, label_de, label_en, unit, price_eur, active, article_number, price_source, erp_synced_at").eq("tool", tool ?? "belt").order("key", { ascending: true });
    if (!includeInactive) query = query.eq("active", true);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data || data.length === 0) {
      return {
        content: [{
          type: "text",
          text: "No pricing components visible for this account. Pricing data requires an admin account."
        }],
        structuredContent: { components: [] }
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { components: data }
    };
  }
});

// src/lib/mcp/tools/build-conveyor-link.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@2.0.2";
import { z as z4 } from "npm:zod@^3.25.76";
var BASE_URL = "https://konfigurator.novamotis.com/belt-conveyor";
var configSchema = {
  frameWidth: z4.number().min(100).max(2e3).default(400).describe("Frame width in mm."),
  beltLength: z4.number().min(500).max(12e3).default(2e3).describe("Belt length in mm."),
  sideGuideHeight: z4.number().min(0).max(300).default(30).describe("Side guide height in mm."),
  inclineAngle: z4.number().min(-10).max(10).default(0).describe("Incline angle in degrees."),
  beltType: z4.enum(["standard", "grip", "heavy-grip", "food-safe"]).default("standard"),
  speed: z4.number().min(1).max(120).default(15).describe("Belt speed in m/min."),
  loadCapacity: z4.number().min(1).max(500).default(50).describe("Load in kg."),
  driveType: z4.enum(["direct", "indirect", "center", "drum"]).default("direct"),
  motorPosition: z4.enum(["left", "right"]).default("left"),
  motorAngle: z4.union([z4.literal(0), z4.literal(90), z4.literal(180), z4.literal(270)]).default(0),
  centerDriveOffset: z4.number().min(0).max(6e3).default(0).describe("Center drive offset in mm."),
  withStand: z4.boolean().default(true),
  standHeight: z4.number().min(300).max(2e3).default(800).describe("Stand height in mm."),
  floorElement: z4.enum(["feet", "castors"]).default("feet"),
  heightAdjust: z4.boolean().default(false),
  floorBolts: z4.boolean().default(false)
};
function toBase64Url(value) {
  const bytes = new TextEncoder().encode(value);
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/g, "");
}
var build_conveyor_link_default = defineTool4({
  name: "build_conveyor_link",
  title: "Build belt conveyor link",
  description: "Turn a belt conveyor specification into a shareable link that opens the configurator with that setup preloaded.",
  inputSchema: {
    ...configSchema,
    step: z4.number().int().min(1).max(5).default(5).describe("Wizard step to open (1-5).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ step, ...config }) => {
    const url = new URL(BASE_URL);
    url.searchParams.set("cfg", toBase64Url(JSON.stringify(config)));
    url.searchParams.set("step", String(step ?? 5));
    const link = url.toString();
    return {
      content: [{ type: "text", text: link }],
      structuredContent: { url: link, config }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "axwgistssiqkuvhcdcam";
var mcp_default = defineMcp({
  name: "configurator",
  title: "Configurator",
  version: "0.1.0",
  instructions: "Tools for the NOVAMOTIS Configurator. Use `list_inquiries` for customer inquiries, `list_configurator_references` to look up reference IDs and their saved configuration, `list_pricing_components` for the price list, and `build_conveyor_link` to create a shareable belt conveyor configuration link.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_inquiries_default,
    list_configurator_references_default,
    list_pricing_components_default,
    build_conveyor_link_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.0.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
